pt_PT
DST-Tools/DSTEd-Languages pull request #3
Opened 2017-07-12 09:47 UTC by hineios

Added translation for European Portuguese

2017-07-12 18:43 UTC, Bizarrus requested changes
Please fix the comments

2017-07-12 18:43 UTC, Bizarrus commented on pt_PT.json
> +  "Asset": "Asset", //I can't find a translation that suits this...
Do not add Comments like this.

2017-07-12 18:43 UTC, Bizarrus commented on pt_PT.json
> +  "<u>W</u>orkspace:": "(<u>W</u>) Área de Trabalho:", //I believe the underline is for shortcut purposes
You can use another character, not only `W`; Please update it for your language specific character. If you dont know, which is a "default", check eclipse IDE or other for a sample.

2017-07-12 18:43 UTC, Bizarrus commented on pt_PT.json
> +  "<u>S</u>earch:": "(<u>S</u>) Procurar:", //once again, shortcuts
See above.

2017-07-12 18:43 UTC, Bizarrus commented on pt_PT.json
> +  "Endianness:": "Extremidade:", //according to Wikipedia
`Endianness` is `Little Endian` or `Big Endian`, for sample.

2017-07-13 09:38 UTC, hineios commented on pt_PT.json
> +  "Asset": "Asset", //I can't find a translation that suits this...
The last commit has no comments...

2017-07-13 09:38 UTC, hineios commented on pt_PT.json
> +  "Endianness:": "Extremidade:", //according to Wikipedia
I double checked and the correct term is that one.

2017-07-13 19:10 UTC, merged